In [ ]:
# Data from JHU at https://github.com/CSSEGISandData/COVID-19
# Referencing two kaggle notebooks:
# (1) https://www.kaggle.com/hotstaff/2019-ncov-cases-global-map-use-github
# (2) https://www.kaggle.com/hotstaff/covid-19-dataset-automatic-generation

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [3]:
import glob

In [4]:
!git clone https://github.com/CSSEGISandData/COVID-19.git

Cloning into 'COVID-19'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 1246 (delta 34), reused 28 (delta 11), pack-reused 1165
Receiving objects: 100% (1246/1246), 30.19 MiB | 22.11 MiB/s, done.
Resolving deltas: 100% (725/725), done.

In [5]:
dailyfiles = sorted(glob.glob('COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/*.csv'))

In [6]:
dailyfiles

['COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-22-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-23-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-24-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-25-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-26-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-27-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-28-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-29-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-30-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/01-31-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-01-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-02-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-03-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-04-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-05-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-06-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-07-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-08-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-09-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-10-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-11-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-12-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-13-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-14-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-15-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-16-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-17-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-18-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-19-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-20-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-21-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-22-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-23-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-24-2020.csv',
 'COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/02-25-2020.csv']

In [7]:
df = pd.concat([pd.read_csv(file) for file in dailyfiles])

In [8]:
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
...,...,...,...,...,...,...
89,"Seattle, WA",US,2020-02-09T07:03:04,1.0,0.0,1.0
90,"Tempe, AZ",US,2020-02-25T21:23:03,1.0,0.0,1.0
91,"Lackland, TX (From Diamond Princess)",US,2020-02-24T23:33:02,0.0,0.0,0.0
92,"Omaha, NE (From Diamond Princess)",US,2020-02-24T23:33:02,0.0,0.0,0.0
93,"Travis, CA (From Diamond Princess)",US,2020-02-24T23:33:02,0.0,0.0,0.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2379 entries, 0 to 93
Data columns (total 6 columns):
Province/State    1718 non-null object
Country/Region    2379 non-null object
Last Update       2379 non-null object
Confirmed         2360 non-null float64
Deaths            1938 non-null float64
Recovered         1991 non-null float64
dtypes: float64(3), object(3)
memory usage: 130.1+ KB

In [19]:
df["Province/State"].unique()

array(['Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu', 'Guangdong',
       'Guangxi', 'Guizhou', 'Hainan', 'Hebei', 'Heilongjiang', 'Henan',
       'Hong Kong', 'Hubei', 'Hunan', 'Inner Mongolia', 'Jiangsu',
       'Jiangxi', 'Jilin', 'Liaoning', 'Macau', 'Ningxia', 'Qinghai',
       'Shaanxi', 'Shandong', 'Shanghai', 'Shanxi', 'Sichuan', 'Taiwan',
       'Tianjin', 'Tibet', 'Washington', 'Xinjiang', 'Yunnan', 'Zhejiang',
       nan, 'Chicago', 'Illinois', 'California', 'Arizona', 'Ontario',
       'New South Wales', 'Victoria', 'British Columbia', 'Bavaria',
       'Queensland', 'Chicago, IL', 'South Australia', 'Boston, MA',
       'Los Angeles, CA', 'Orange, CA', 'Santa Clara, CA', 'Seattle, WA',
       'Tempe, AZ', 'San Benito, CA', 'Toronto, ON', 'London, ON',
       'Madison, WI', 'Cruise Ship', 'Diamond Princess cruise ship',
       'San Diego County, CA', 'San Antonio, TX', 'Ashland, NE',
       'Travis, CA', 'From Diamond Princess', 'Lackland, TX', 'None',
       'Humboldt County, CA', 'Sacramento County, CA',
       'Omaha, NE (From Diamond Princess)',
       'Travis, CA (From Diamond Princess)',
       'Lackland, TX (From Diamond Princess)',
       'Unassigned Location (From Diamond Princess)'], dtype=object)

In [20]:
df["Country/Region"].unique()

array(['Mainland China', 'Hong Kong', 'Macau', 'Taiwan', 'US', 'Japan',
       'Thailand', 'South Korea', 'Singapore', 'Philippines', 'Malaysia',
       'Vietnam', 'Australia', 'Mexico', 'Brazil', 'Colombia', 'France',
       'Nepal', 'Canada', 'Cambodia', 'Sri Lanka', 'Ivory Coast',
       'Germany', 'Finland', 'United Arab Emirates', 'India', 'Italy',
       'UK', 'Russia', 'Sweden', 'Spain', 'Belgium', 'Others', 'Egypt',
       'Iran', 'Israel', 'Lebanon', 'Iraq', 'Oman', 'Afghanistan',
       'Bahrain', 'Kuwait', 'Austria', 'Algeria', 'Croatia',
       'Switzerland'], dtype=object)

In [21]:
# fill NaN
df = df.fillna({"Province/State": 'None'})

# Change astype
df["Last Update"] = pd.to_datetime(df["Last Update"])
df["Confirmed"] = df["Confirmed"].fillna(0).astype('int')
df["Deaths"] = df["Deaths"].fillna(0).astype('int')
df["Recovered"] =df["Recovered"].fillna(0).astype('int')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2379 entries, 0 to 93
Data columns (total 6 columns):
Province/State    2379 non-null object
Country/Region    2379 non-null object
Last Update       2379 non-null datetime64[ns]
Confirmed         2379 non-null int64
Deaths            2379 non-null int64
Recovered         2379 non-null int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 130.1+ KB

In [ ]:
df.info()